version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev  # 개발용 Dockerfile 사용
    ports:
      - "8080:8080"
    depends_on:
      influxdb:
        condition: service_healthy
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - INFLUXDB_URL=${INFLUXDB_URL}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_DATABASE=${INFLUXDB_DATABASE}
      - INFLUXDB_ORGANIZATION=${INFLUXDB_ORGANIZATION}
      - API_KEY=${API_KEY}
      - REDIS_URL=${REDIS_URL}
      - REDIS_PORT=${REDIS_PORT}
    volumes:
      - ./:/app  # 소스 코드 마운트
      - ~/.gradle:/root/.gradle  # Gradle 캐시 공유
    networks:
      - app-network

  postgresql:
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    ports:
      - "7777:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d test -U inderby" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app-network

  influxdb:
    build:
      context: ./influxdb
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=${INFLUXDB_INIT_MODE}
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORGANIZATION}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_DATABASE}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
    volumes:
      - influxdb-data:/var/lib/influxdb2
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8086/health" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app-network
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    external: true
    name: bems-network

volumes:
  postgres-data:
  influxdb-data:
  redis-data: